package by.itacademy.javaenterprise.goralchuk.entity;

import lombok.Getter;

public enum Specialization {
    THERAPIST,
    ALLERGIST,
    DERMATOLOGIST,
    CARDIOLOGIST,
    GYNECOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    NEPHROLOGIST,
    UROLOGIST,
    PULMONOLOGIST,
    OTOLARYNGOLOGIST,
    NEUROLOGIST,
    PSYCHIATRIST,
    ONCOLOGIST,
    RADIOLOGIST,
    RHEUMATOLOGIST,
    GENERAL_SURGEON,
    ORTHOPEDIC_SURGEON,
    CARDIAC_SURGEON,
    ANESTHESIOLOGIST;
}
