CREATE TABLE addresses (
address_id BIGINT NOT NULL AUTO_INCREMENT,
post_code BIGINT NULL DEFAULT NULL,
city CHAR(50) NULL DEFAULT NULL,
street CHAR(50) NULL DEFAULT NULL,
house_number INT(10) NULL DEFAULT NULL,
apartment_number INT(10) NULL DEFAULT NULL,
phone_number INT(12) NULL DEFAULT NULL,
PRIMARY KEY (address_id)
);

